name: Daily Database Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Authenticate with PAT
        run: |
          git remote add origin_with_token https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
      - name: Run update script
        run: |
          bash test-all-domains.sh > results
          if [[ $(git diff results) ]]; then
            git add results
            git commit -m "automated update: results"
            git push origin_with_token
          fi
